// <auto-generated />
using System;
using Desnz.Chmm.Obligation.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Desnz.Chmm.Obligation.Api.Migrations
{
    [DbContext(typeof(ObligationContext))]
    partial class ObligationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Desnz.Chmm.Obligation.Api.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime>("DateOfTransaction")
                        .HasColumnType("timestamptz");

                    b.Property<bool>("IsExcluded")
                        .HasColumnType("boolean");

                    b.Property<int>("Obligation")
                        .HasColumnType("integer");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SchemeYearId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SchemeYearQuarterId")
                        .HasColumnType("uuid");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SchemeYearId", "OrganisationId", "TransactionType")
                        .IsUnique()
                        .HasFilter("\"TransactionType\" = 'CarryForward' OR \"TransactionType\" = 'BroughtForward'");

                    b.HasIndex("SchemeYearId", "TransactionType", "DateOfTransaction")
                        .IsDescending();

                    b.HasIndex("SchemeYearId", "OrganisationId", "IsExcluded", "DateOfTransaction")
                        .IsDescending();

                    b.HasIndex("SchemeYearId", "OrganisationId", "TransactionType", "DateOfTransaction")
                        .IsDescending();

                    b.HasIndex("SchemeYearId", "SchemeYearQuarterId", "OrganisationId", "TransactionType", "DateOfTransaction")
                        .IsDescending();

                    b.ToTable("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
