// <auto-generated />
using System;
using Desnz.Chmm.Identity.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Desnz.Chmm.Identity.Api.Migrations
{
    [DbContext(typeof(IdentityContext))]
    [Migration("20231018131334_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChmmRoleChmmUser", b =>
                {
                    b.Property<Guid>("ChmmRolesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChmmUsersId")
                        .HasColumnType("uuid");

                    b.HasKey("ChmmRolesId", "ChmmUsersId");

                    b.HasIndex("ChmmUsersId");

                    b.ToTable("ChmmRoleChmmUser");
                });

            modelBuilder.Entity("Desnz.Chmm.Identity.Common.Entities.ChmmRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ChmmRoles");
                });

            modelBuilder.Entity("Desnz.Chmm.Identity.Common.Entities.ChmmUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ChmmUsers");
                });

            modelBuilder.Entity("ChmmRoleChmmUser", b =>
                {
                    b.HasOne("Desnz.Chmm.Identity.Common.Entities.ChmmRole", null)
                        .WithMany()
                        .HasForeignKey("ChmmRolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Desnz.Chmm.Identity.Common.Entities.ChmmUser", null)
                        .WithMany()
                        .HasForeignKey("ChmmUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
